version: 0.2

phases:
  install:
    commands:
      - cd 04_dynamo
      - ls
    #   - ./deploy.sh -i
  build:
    commands:
    #   - ./deploy.sh -b
    - echo 1
  post_build:
    commands:
    #   - ./deploy.sh -d
    - echo 2
